### ISSUE TITLE
Favicon support?

### ISSUE THREAD

**Issue by eduwass** [addozhang/alfred-safari-toolkit#1]
Hey Addo,

I'm so glad I stumbled upon this repo, I love the workflow, use it daily! 👍

I was wondering if it would be possible to implement favicons like https://github.com/tupton/alfred-chrome-history ?

I was checking and see that Safari stores a favicon cache in `~/Library/Safari/Favicon Cache`, any thoughts?

Thanks!

**Comment by addozhang** [comment]
It's a good idea. Let me check it later.

**Comment by addozhang** [comment]
@eduwass Bad news here. Chrome is storing both url and bitmap of favicon in db while Safari is storing only favicon url in db.

The favicon cache you mentioned above is the behavior of Safari and there is no relation between favicon url and cached file. So it's difficult to attaching favicon in result list except fetching from internet for each during search.

If you have any good idea about this, please let me know.

**Comment by eduwass** [comment]
Hey @addozhang 

firstly, thanks! 🙏  

Appreciate that you took some of your time to look into this.

OK, so basically you're running into the problem mentioned here right?

- [How to correlate Safari’s favicon in cache with URL](https://apple.stackexchange.com/questions/439887/how-to-correlate-safari-s-favicon-in-cache-with-url)

If that is the case it is unfortunate yeah, probably means that you are stuck with needing your own icon cache.

This is all I found in that regard:

- [Show icon from url in script results](https://www.alfredforum.com/topic/16647-show-icon-from-url-in-script-results/)
- [Script Filter Icon from URL](https://www.alfredforum.com/topic/3873-script-filter-icon-from-url/)

**Comment by addozhang** [comment]
@eduwass Great job, let me walk through them. Thanks.

**Comment by addozhang** [comment]
@eduwass Referring to your suggestion, just released 1.3.0-rc1 to support favicon. At the same time, limit 50 items in the result list. Tell me if you find any issues.

**Comment by eduwass** [comment]
Hey @addozhang , 

that is awesome!! 

Unfortunately, I haven't been able to get it to work though, I've installed [the latest release](https://github.com/addozhang/alfred-safari-toolkit/releases/tag/v1.0.3-rc1) but haven't seen any icons yet.

**Log (only showing Interesting Information)**
```
[23:12:58.092] STDERR: Safari Toolkit[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.323AC0F5-62A9-4CBC-BFA2-CB230E19EC12%3EADCEDA69-7C6C-4981-845E-8551F9FB3BFE)] 🍺
23:12:57 workflow.go:328: ----- Safari Toolkit/1.0.3-rc1 (AwGo/0.27.1) -----
23:12:57 update.go:286: no cached releases
23:12:57 update.go:195: no downloads available
23:12:58 feedback.go:509: Sent 50 result(s) to Alfred
23:12:58 workflow.go:405: ------------------ 215.985709ms ------------------
```

Where is the cachedir supposed to exist? 

I've looked at:
- https://pkg.go.dev/github.com/jason0x43/go-alfred#Workflow.CacheDir
- https://alfred-workflow.readthedocs.io/en/latest/user-manual/persistent-data.html


Think that implies I should see the favicons cache at in `~/Library/Application Support` or `~/Library/Caches` but I'm not seeing anything there.

Wondering if that might be the problem.

Let me know if there's anything I can do to help debug.

Thanks!

**Comment by eduwass** [comment]
Actually, **favicon folder does exist,** looks like what is happening is that it is never actually downloading the file, here's a log (I've [added some pritnf's to the logs](https://github.com/eduwass/alfred-safari-toolkit/commit/079d6c3154d73affd48a7308b4fc4949e0751acc))

```
[23:43:30.771] STDERR: Safari Toolkit[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.323AC0F5-62A9-4CBC-BFA2-CB230E19EC12%3EADCEDA69-7C6C-4981-845E-8551F9FB3BFE)] 
23:43:30 main.go:21: init icon cache /Users/eduwass/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/com.atbug.workflow.safari/favicons
🍺
23:43:30 workflow.go:328: ----- Safari Toolkit/1.0.3-rc1 (AwGo/0.27.1) -----
23:43:30 update.go:286: no cached releases
23:43:30 update.go:195: no downloads available
23:43:30 favicon.go:28: lookupFavicon https://github.com/addozhang/alfred-safari-toolkit
23:43:30 favicon.go:28: lookupFavicon https://pkg.go.dev/github.com/jason0x43/go-alfred#section-readme
23:43:30 favicon.go:78: downloadIcon https://github.githubassets.com/favicons/favicon-dark.png
23:43:30 favicon.go:28: lookupFavicon https://pkg.go.dev/github.com/jason0x43/go-alfred
23:43:30 favicon.go:78: downloadIcon https://pkg.go.dev/static/shared/icon/favicon.ico
...
23:43:30 feedback.go:509: Sent 50 result(s) to Alfred
23:43:30 workflow.go:405: ------------------ 198.413375ms ------------------
```


From the log I understand that [downloadIcon](https://github.com/addozhang/alfred-safari-toolkit/blob/aa2264ebdc42fcfe810d84288705d9bdef22c062/favicon.go#L76) is not actually downloading the file for some reason.

Let me know if you have any ideas, thanks again for your help!

**Comment by addozhang** [comment]
@eduwass I found the issue now. The background downloading process was interrupted when the searching was complete. If waiting for the download complete, it will hang the search representation.

The favicon cache mechanism of chrome and safari is different—the former stores icon data in the database directly, and the latter does not. If downloading during searching, it must affect the experience. 

So I think it is better to remove this feature. What do you think?

I moved the favicon commits to `dev` branch.

**Comment by eduwass** [comment]
Hey @addozhang ,

Hmm, OK; is that something that is fixable?

Personally, I'd love to get this feature working, but it's your work so you should be the one making that decision in the end. Maybe you could make it an optional feature that people can turn on or off?

Thanks!

**Comment by addozhang** [comment]
Hi @eduwass, I will be still seeking a better solution for it. Totally agree with you that the favicon is a nice feature.

**Comment by skobylite** [comment]
Following for this, I love that you've been looking to fix this functionality! Hopefully there's a way to produce search results without waiting for download to complete
