### ISSUE TITLE
Workflow not showing history

### ISSUE THREAD

**Issue by rollokd** [addozhang/alfred-safari-toolkit#2]
just installed your workflow, once I got the permissions right, I tried to use it but when I put the keyword trigger into Alfred it doesn't show anything and I get this error in the debug panel in Alfred. Not sure if this is a problem with my system or the workflow but would love some advice
<img width="572" alt="Screenshot 2022-06-19 at 11 24 19 pm" src="https://user-images.githubusercontent.com/75755077/174502544-f29e0919-5e95-48f9-80a2-dcbc8dfc0b63.png">

**Comment by ymostudio** [comment]
Same here.
Thanks for developing this though!

**Comment by addozhang** [comment]
Hi @rollokd @ymostudio, thanks for feedback. Which version installed?

**Comment by ymostudio** [comment]
Hi @rollokd 
Latest from here on Github — never used it before, so it's not that it has stopped working. 
Also latest version of Alfred on macOS Catalina 10.15.7
Cheers

**Comment by addozhang** [comment]
@rollokd which version and platform your alfred running on? Currently, I just have m1 and macOS 12.3 to test.

**Comment by ymostudio** [comment]
@rollokd as mentioned:
> latest version of Alfred on macOS Catalina 10.15.7
Thanks

**Comment by addozhang** [comment]
Hi @ymostudio, thanks for feedback. I got it from your comment above. I want to know the information of @rollokd. Then I will try to troubleshooting whether it's issue with platform.

> @rollokd as mentioned:
> 
> > latest version of Alfred on macOS Catalina 10.15.7
> > Thanks

**Comment by rollokd** [comment]
Hi @addozhang, I’m using a 2019 Intel MacBook Pro 16 inch and am running macOS Monterey 12.3 with the latest version of Alfred.

**Comment by addozhang** [comment]
> Hi @addozhang, I’m using a 2019 Intel MacBook Pro 16 inch and am running macOS Monterey 12.3 with the latest version of Alfred.

@rollokd got it. I will find a intel device to test it.

**Comment by SpiritOba** [comment]
Very good, it's macOS 12.4, Intel can't use it，when can it be used。

**Comment by addozhang** [comment]
@peeter110 thanks for feedback. I just got a Intel one from friend and will try to fix it.

**Comment by addozhang** [comment]
Hi @peeter110 @rollokd @ymostudio, [v1.0.3](https://github.com/addozhang/alfred-safari-toolkit/releases/tag/v1.0.3) was released. Please update and let me the result.

Thanks.

**Comment by peeter110** [comment]
macOS12.4，It's fine to use, but why not show the last few records？

**Comment by SpiritOba** [comment]
macOS12.4，No problem to use。Master might

**Comment by peeter110** [comment]
<img width="570" alt="截屏2022-07-04 19 32 38" src="https://user-images.githubusercontent.com/56115849/177146356-97a6e11a-0c1b-487a-9625-33f473c23db4.png">

**Comment by addozhang** [comment]
@peeter110 Thanks.
